=== api-evangelist/opentripmap/json-schema/simplesuggestfeature.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/opentripmap/refs/heads/main/json-schema/simplesuggestfeature.json",
  "title": "SimpleSuggestFeature",
  "required": [
    "xid",
    "name",
    "highlighted_name",
    "kinds",
    "point"
  ],
  "type": "object",
  "properties": {
    "xid": {
      "description": "Unique identifier of the object in OpenTripMap",
      "type": "string"
    },
    "name": {
      "description": "The name of the object",
      "type": "string"
    },
    "highlighted_name": {
      "description": "The name of the object with highlighted search term",
      "type": "string"
    },
    "kinds": {
      "description": "Comma-separated list of categories. [see List of categories](https://dev.opentripmap.com/en/catalog.tree.json)",
      "type": "string"
    },
    "osm": {
      "description": "OpenStreetMap identifier of the object",
      "type": "string"
    },
    "wikidata": {
      "description": "Wikidata  identifier of the object",
      "type": "string"
    },
    "dist": {
      "description": "Distance in meters from selected point (for radius query)",
      "type": "number",
      "format": "double"
    },
    "point": {
      "type": "object",
      "description": "Point location of the object",
      "properties": {
        "lon": {
          "description": "Longitude",
          "type": "number",
          "format": "double"
        },
        "lat": {
          "description": "Latitude",
          "type": "number",
          "format": "double"
        }
      }
    }
  },
  "example": {
    "xid": "N890538405",
    "rate": 1,
    "highlighted_name": "<b>Don</b> Este",
    "name": "Don Este",
    "osm": "node/890538405",
    "dist": 456.55705702,
    "kinds": "foods,fast_food,tourist_facilities",
    "point": {
      "lon": -70.645576,
      "lat": -33.438782
    }
  }
}

=== api-evangelist/opentripmap/examples/autosuggest-response.json
[
  {
    "xid": "N6274014481",
    "name": "Eiffel Tower",
    "highlighted_name": "<b>Eiffel</b> Tower",
    "kinds": "architecture,towers,interesting_places",
    "point": {
      "lon": 2.29448,
      "lat": 48.85837
    }
  },
  {
    "xid": "W305023984",
    "name": "Eiffel Tower Area",
    "highlighted_name": "<b>Eiffel</b> Tower Area",
    "kinds": "natural,parks",
    "point": {
      "lon": 2.29376,
      "lat": 48.85629
    }
  }
]
